version: '2'

services:

  node:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    links: 
      - mongodb
  mongodb:
    container_name: mongo
    build: ./mongo
    env_file: .env
    volumes:
      - ./mongo/data:/data/db
    ports:
      - "27017:27017"
